<?php

namespace ContainerX4RJBj9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DlPwY1OService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dlPwY1O' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dlPwY1O'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ParticipantesRepository' => ['privates', 'App\\Repository\\ParticipantesRepository', 'getParticipantesRepositoryService', true],
        ], [
            'ParticipantesRepository' => 'App\\Repository\\ParticipantesRepository',
        ]);
    }
}
