<?php

namespace ContainerX4RJBj9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IGl4ffXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iGl4ffX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iGl4ffX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ParticipantesRepository' => ['privates', 'App\\Repository\\ParticipantesRepository', 'getParticipantesRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'ParticipantesRepository' => 'App\\Repository\\ParticipantesRepository',
            'entityManager' => '?',
        ]);
    }
}
