<?php

namespace ContainerX4RJBj9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZB6OshVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zB6OshV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zB6OshV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\LoginController::create' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\LoginController::index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ParticipantesController::agregarParticipante' => ['privates', '.service_locator.2YPAqlo', 'get_ServiceLocator_2YPAqloService', true],
            'App\\Controller\\ParticipantesController::carreracampo' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController::carrerafin' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController::crearParticipante' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ParticipantesController::eliminar' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ParticipantesController::eliminar_campo' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ParticipantesController::enviokit' => ['privates', '.service_locator.WZeIXfO', 'get_ServiceLocator_WZeIXfOService', true],
            'App\\Controller\\ParticipantesController::estadisticas' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController::fin2024' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController::importar' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ParticipantesController::index' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController::invitacion' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController::numeros' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController::pruebaemail' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ParticipantesController::sendEmailagain' => ['privates', '.service_locator.2YPAqlo', 'get_ServiceLocator_2YPAqloService', true],
            'App\\Controller\\ParticipantesController::sendEmailprueba' => ['privates', '.service_locator.2YPAqlo', 'get_ServiceLocator_2YPAqloService', true],
            'App\\Controller\\ParticipantesController::verParticipante' => ['privates', '.service_locator.dlPwY1O', 'get_ServiceLocator_DlPwY1OService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\LoginController:create' => ['privates', '.service_locator.ESgEUJd', 'get_ServiceLocator_ESgEUJdService', true],
            'App\\Controller\\LoginController:index' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Controller\\ParticipantesController:agregarParticipante' => ['privates', '.service_locator.2YPAqlo', 'get_ServiceLocator_2YPAqloService', true],
            'App\\Controller\\ParticipantesController:carreracampo' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController:carrerafin' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController:crearParticipante' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ParticipantesController:eliminar' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ParticipantesController:eliminar_campo' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ParticipantesController:enviokit' => ['privates', '.service_locator.WZeIXfO', 'get_ServiceLocator_WZeIXfOService', true],
            'App\\Controller\\ParticipantesController:estadisticas' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController:fin2024' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController:importar' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ParticipantesController:index' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController:invitacion' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController:numeros' => ['privates', '.service_locator.iGl4ffX', 'get_ServiceLocator_IGl4ffXService', true],
            'App\\Controller\\ParticipantesController:pruebaemail' => ['privates', '.service_locator.uVvF4gL', 'get_ServiceLocator_UVvF4gLService', true],
            'App\\Controller\\ParticipantesController:sendEmailagain' => ['privates', '.service_locator.2YPAqlo', 'get_ServiceLocator_2YPAqloService', true],
            'App\\Controller\\ParticipantesController:sendEmailprueba' => ['privates', '.service_locator.2YPAqlo', 'get_ServiceLocator_2YPAqloService', true],
            'App\\Controller\\ParticipantesController:verParticipante' => ['privates', '.service_locator.dlPwY1O', 'get_ServiceLocator_DlPwY1OService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\LoginController::create' => '?',
            'App\\Controller\\LoginController::index' => '?',
            'App\\Controller\\ParticipantesController::agregarParticipante' => '?',
            'App\\Controller\\ParticipantesController::carreracampo' => '?',
            'App\\Controller\\ParticipantesController::carrerafin' => '?',
            'App\\Controller\\ParticipantesController::crearParticipante' => '?',
            'App\\Controller\\ParticipantesController::eliminar' => '?',
            'App\\Controller\\ParticipantesController::eliminar_campo' => '?',
            'App\\Controller\\ParticipantesController::enviokit' => '?',
            'App\\Controller\\ParticipantesController::estadisticas' => '?',
            'App\\Controller\\ParticipantesController::fin2024' => '?',
            'App\\Controller\\ParticipantesController::importar' => '?',
            'App\\Controller\\ParticipantesController::index' => '?',
            'App\\Controller\\ParticipantesController::invitacion' => '?',
            'App\\Controller\\ParticipantesController::numeros' => '?',
            'App\\Controller\\ParticipantesController::pruebaemail' => '?',
            'App\\Controller\\ParticipantesController::sendEmailagain' => '?',
            'App\\Controller\\ParticipantesController::sendEmailprueba' => '?',
            'App\\Controller\\ParticipantesController::verParticipante' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\LoginController:create' => '?',
            'App\\Controller\\LoginController:index' => '?',
            'App\\Controller\\ParticipantesController:agregarParticipante' => '?',
            'App\\Controller\\ParticipantesController:carreracampo' => '?',
            'App\\Controller\\ParticipantesController:carrerafin' => '?',
            'App\\Controller\\ParticipantesController:crearParticipante' => '?',
            'App\\Controller\\ParticipantesController:eliminar' => '?',
            'App\\Controller\\ParticipantesController:eliminar_campo' => '?',
            'App\\Controller\\ParticipantesController:enviokit' => '?',
            'App\\Controller\\ParticipantesController:estadisticas' => '?',
            'App\\Controller\\ParticipantesController:fin2024' => '?',
            'App\\Controller\\ParticipantesController:importar' => '?',
            'App\\Controller\\ParticipantesController:index' => '?',
            'App\\Controller\\ParticipantesController:invitacion' => '?',
            'App\\Controller\\ParticipantesController:numeros' => '?',
            'App\\Controller\\ParticipantesController:pruebaemail' => '?',
            'App\\Controller\\ParticipantesController:sendEmailagain' => '?',
            'App\\Controller\\ParticipantesController:sendEmailprueba' => '?',
            'App\\Controller\\ParticipantesController:verParticipante' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
