<?php

namespace ContainerX4RJBj9;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParticipantesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ParticipantesController' shared autowired service.
     *
     * @return \App\Controller\ParticipantesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ParticipantesController.php';

        $container->services['App\\Controller\\ParticipantesController'] = $instance = new \App\Controller\ParticipantesController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\ParticipantesController', $container));

        return $instance;
    }
}
