<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX4RJBj9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX4RJBj9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX4RJBj9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX4RJBj9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX4RJBj9\App_KernelDevDebugContainer([
    'container.build_hash' => 'X4RJBj9',
    'container.build_id' => '8f80f07f',
    'container.build_time' => 1741196117,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX4RJBj9');
